# name: 'Add comment on issue'
# on:
#   issues:
#     types:
#       - labeled
# jobs:
#   add-comment:
#     if: github.event.label.name == 'help-wanted'
#     runs-on: ubuntu-latest
#     permissions:
#       issues: write
#     steps:
#       - name: Add comment
#         uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
#         with:
#           issue-number: ${{ github.event.issue.number }}
#           body: |
#             This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:

          
name: 'Warns and Closes Stale Issues'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  handle_stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/stale@main
        id: stale
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is has been labelled stale. Remove the label or label it important if you are not satistfied'
          
          days-before-stale: 1
          days-before-close: 2

